apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    port: 3306

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-dp-sc
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  allowAutoIOPSPerGBIncrease: 'true'
  encrypted: 'true'

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dp-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: ebs-dp-sc

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS app;
    CREATE USER 'app'@'%' IDENTIFIED BY 'app12345';
    GRANT ALL PRIVILEGES ON app.* TO 'app'@'%';

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret-info
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: azhzMTIzNDUK
  MYSQL_DATABASE: YXBwCg==
  MYSQL_USER: YXBwCg==
  MYSQL_PASSWORD: YXBwMTIzNDUK

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers:
        - name: mysql-container
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: db-secret-info
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: ebs-dp-claim
        - name: initdb
          configMap:
            name: mysql-init
